[package]
name = "crab_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
clightningrpc-common = "0.3.0-beta.2"
clightningrpc-plugin = "0.3.0-beta.2"
clightningrpc-plugin-macros = "0.3.0-beta.2"
serde_json = "1.0"